name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: testing

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install Dependencies
      - name: Install Dependencies
        run: |
             cd /home/ubuntu/App/actions-runner/_work/Leadtap_project/Leadtap_project/app
             npm ci


      # SAST - SonarQube Scan
      - name: SonarQube Scan
        run: |
          sonar-scanner \
              -Dsonar.projectKey=nextjs-app \
              -Dsonar.host.url=http://${{ secrets.SONAR_HOST }}:9000 \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
              -Dsonar.sources=.

      # Wait for Quality Gate#
      - name: Check SonarQube Quality Gate
        run: |
          echo "Waiting for SonarQube Quality Gate..."
          sleep 5

          STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
          "http://${{ secrets.SONAR_HOST }}:9000/api/qualitygates/project_status?projectKey=nextjs-app" \
          | jq -r '.projectStatus.status')

          echo "Quality Gate Status: $STATUS"

          if [ "$STATUS" != "OK" ]; then
            echo "Quality Gate Failed. Stopping pipeline."
            exit 1
          fi
      
      # SCA
      - name: SCA - Dependency Security Check
        run: |
            npm audit fix --force || true  # --force → forces major version upgrades (can break app)
            npm audit --audit-level=high
            
      # Deploy to EC2
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: devops
          port: 222
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            bash
            cd /home/devops/Leadtap_project
            git pull origin main
            cd /home/devops/Leadtap_project/app
            npm install --no-audit --no-fund
            npm run build
            pm2 restart all

      # DAST - OWASP ZAP Scan (Post-deploy)
      - name: OWASP ZAP Baseline Scan
        run: |
          sudo docker run --rm \
            --network host \
            -v "$(pwd):/zap/wrk" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t https://${{ secrets.DOMAIN }} \
            -r zap-report-${{ github.sha }}.html || true
